### ISSUE TITLE
Collect resources for CI + django setup

### ISSUE THREAD

**Issue by surchs** [metaneuro/concept_query#60]
We need some good tutorials, or guidelines to set up CI testing for our django project. 

- [ ] what configs do we need 
- [ ] any accounts to figure out
- [ ] what are the next steps to set up CI
- [ ] how and what containerization do we need

**Comment by surchs** [comment]
@jarmoza: any thoughts on this so far? Should we start a document for ourselves on what you have found out?

**Comment by jarmoza** [comment]
Getting close to that documentation step now. After running through Docker tutorials, my next step is dockerizing the app with plain python Docker image, making sure it's working, and then will transition to the CircleCI docker image and Circle CI's docker executor.

**Comment by surchs** [comment]
@jarmoza: do you think we can wrap this step up?

**Comment by jarmoza** [comment]
Yes, definitely. I was staring at this one yesterday figuring out if it can be closed. I think this issue is a good example of overly-broad tasks that could be subdivided.

I compiled this document on CircleCI articles/docs read yesterday for this effort.

https://docs.google.com/document/d/1HoxyXhkTcSerM0j8upMZ1axCOX-iObwBPhFx0U-W38U/edit
